(package "flycheck-deno"
         "0.1.0"
         "Flycheck for deno-lint")

(website-url "https://github.com/jcs-elpa/flycheck-deno")
(keywords "lisp" "deno")

(package-file "flycheck-deno.el")

(script "test" "echo \"Error: no test specified\" && exit 1")

(source "melpa")

(depends-on "emacs" "26.1")
(depends-on "flycheck")

(setq network-security-level 'low)  ; see https://github.com/jcs090218/setup-emacs-windows/issues/156#issuecomment-932956432
